### ISSUE TITLE
Atom Helper high CPU when enabled

### ISSUE THREAD

**Issue by kevinansfield** [josa42/atom-ide-ember#1] opened 2017-10-13 08:46 UTC
When I have this package enabled I end up with an Atom Helper process sitting at 50-60% CPU constantly.

I've tried grabbing a profile using Atom's developer tools but that didn't provide any insights as it seemed to only profile the main Atom process.

Is there anything I can do to help diagnose?

**Comment by josa42** [comment] 2017-11-19 10:44
This is a known issue with [emberwatch/ember-language-server](https://github.com/emberwatch/ember-language-server) (For example see emberwatch/ember-language-server#54).

As far as I know the issue is related to [chokidar](https://github.com/paulmillr/chokidar) which is used to watch file changes in [emberwatch/ember-language-server](https://github.com/emberwatch/ember-language-server). There is also an issue regarding high cpu usage on macOS: paulmillr/chokidar#597.

I did some experiments with using the system installed `node` version instead of the one bundled in atom, with mixed results.

**Comment by t-sauer** [comment] 2018-04-24 22:16
The problem was fixed in the last ember-language-server release (0.2.0) so I think upgrading the version in here should fix the problem in Atom as well.

**Closed as completed** 2018-10-11 22:45 UTC
Labels: bug
